-- =====================================================================
-- Library Manager API - schema (PostgreSQL)
-- Idempotent: runs on every startup (spring.sql.init.mode=always) and
-- never drops data. To start from scratch use db/reset.sql.
-- =====================================================================

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    email    VARCHAR(150) NOT NULL,
    password VARCHAR(100) NOT NULL,
    status   VARCHAR(20)  NOT NULL,
    role     VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_users_email        UNIQUE (email),
    CONSTRAINT ck_users_email_lower  CHECK (email = LOWER(email)),
    CONSTRAINT ck_users_status       CHECK (status IN ('ACTIVO', 'SANCIONADO')),
    CONSTRAINT ck_users_role         CHECK (role IN ('ADMIN', 'BIBLIOTECARIO', 'LECTOR'))
);

CREATE TABLE IF NOT EXISTS books (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn            VARCHAR(20)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    author          VARCHAR(150) NOT NULL,
    category        VARCHAR(100) NOT NULL,
    total_stock     INTEGER      NOT NULL,
    available_stock INTEGER      NOT NULL,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_books_isbn         UNIQUE (isbn),
    CONSTRAINT ck_books_total_stock  CHECK (total_stock >= 0),
    -- Last line of defence against overselling / double return:
    CONSTRAINT ck_books_available    CHECK (available_stock >= 0 AND available_stock <= total_stock)
);

CREATE TABLE IF NOT EXISTS loans (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT      NOT NULL,
    book_id              BIGINT      NOT NULL,
    loan_date            DATE        NOT NULL,
    expected_return_date DATE        NOT NULL,
    actual_return_date   DATE,
    status               VARCHAR(20) NOT NULL,
    CONSTRAINT fk_loans_user   FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_loans_book   FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT ck_loans_status CHECK (status IN ('ACTIVO', 'DEVUELTO', 'ATRASADO')),
    CONSTRAINT ck_loans_dates  CHECK (expected_return_date >= loan_date),
    -- A loan has a real return date if and only if it is DEVUELTO:
    CONSTRAINT ck_loans_return CHECK ((status = 'DEVUELTO') = (actual_return_date IS NOT NULL))
);

-- ---------------------------------------------------------------------
-- Indexes (users.email and books.isbn are already indexed by their UNIQUE constraints)
-- ---------------------------------------------------------------------
-- Catalog filters (case-insensitive category equality, title prefix search)
CREATE INDEX IF NOT EXISTS idx_books_category_lower ON books (LOWER(category));
CREATE INDEX IF NOT EXISTS idx_books_title_lower    ON books (LOWER(title) text_pattern_ops);

-- Loan limit check and overdue detection for one reader
CREATE INDEX IF NOT EXISTS idx_loans_user_status    ON loans (user_id, status);
-- GET /prestamos/atrasados
CREATE INDEX IF NOT EXISTS idx_loans_status_expected ON loans (status, expected_return_date);
-- FK lookups / blocking deletion of books with open loans
CREATE INDEX IF NOT EXISTS idx_loans_book           ON loans (book_id);
-- GET /prestamos/mis-prestamos (newest first)
CREATE INDEX IF NOT EXISTS idx_loans_user_loan_date ON loans (user_id, loan_date DESC);